// Generated by https://quicktype.io


import 'package:woofriend/features/auth/domain/entities/user.dart';

class Animal {
  String id;
  String typeanimal;
  String name;
  String birthdate;
  String race;
  String characteristics;
  String vaccinationrecord;
  String pathologiesdisabilities;
  String photo;
  User? user;

  Animal({
    required this.id,
    required this.typeanimal,
    required this.name,
    required this.birthdate,
    required this.race,
    required this.characteristics,
    this.vaccinationrecord = "",
    this.pathologiesdisabilities= "",
    this.photo = "",
    this.user,
  });
}
